AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a role to Management Account so that CID data collection can assume to read
Parameters:
  DataCollectionAccountID:
    Type: String
    Description: AccountId of where the collector is deployed
  ManagementAccountRole:
    Type: String
    Description: Name of role deployed into Management account to read high level data
    Default: "Lambda-Assume-Role-Management-Account"
  RolePrefix:
    Type: String
    Description: This prefix will be placed in front of all roles created. Note you may wish to add a dash at the end to make more readable e.g. prefix-
    Default: "WA-"
Outputs:
  LambdaRole:
    Description: Role for lambda to assume in cost account
    Value: !GetAtt LambdaRole.Arn
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${RolePrefix}${ManagementAccountRole}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                -  !Sub "arn:aws:iam::${DataCollectionAccountID}:root"
            Condition:
              ForAnyValue:ArnEquals:
                aws:PrincipalArn:
                  - !Sub "arn:aws:iam::${DataCollectionAccountID}:role/${RolePrefix}account-collector-LambdaRole"
                  - !Sub "arn:aws:iam::${DataCollectionAccountID}:role/${RolePrefix}Lambda-Role-organization"
                  - !Sub "arn:aws:iam::${DataCollectionAccountID}:role/${RolePrefix}Lambda-Role-compute-optimizer"
                  - !Sub "arn:aws:iam::${DataCollectionAccountID}:role/${RolePrefix}Lambda-Role-cost-explorer-cost-anomaly"
                  - !Sub "arn:aws:iam::${DataCollectionAccountID}:role/${RolePrefix}Lambda-Role-cost-explorer-rightsizing"
      Path: /
      Policies:
        - PolicyName: "Management-Account-permissions"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "organizations:ListAccountsForParent"
                  - "organizations:DescribeAccount"
                  - "organizations:ListParents"
                  - "organizations:ListRoots"
                  - "organizations:ListChildren"
                  - "organizations:ListTagsForResource"
                  - "organizations:ListAccounts"
                  - "organizations:DescribeOrganizationalUnit"
                  - "organizations:ListCreateAccountStatus"
                  - "organizations:DescribeOrganization"
                  - "organizations:ListOrganizationalUnitsForParent"
                Resource: "*"
        - PolicyName: "RightsizingModule"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ce:GetRightsizingRecommendation"
                Resource: "*"
        - PolicyName: "AnomaliesModule"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ce:GetAnomalies"
                Resource: "*"
        - PolicyName: "ComputeOptimizer-ExportLambdaFunctionRecommendations"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "compute-optimizer:ExportLambdaFunctionRecommendations"
                  - "compute-optimizer:GetLambdaFunctionRecommendations"
                  - "lambda:ListFunctions"
                  - "lambda:ListProvisionedConcurrencyConfigs"
                Resource: "*"
        - PolicyName: "ComputeOptimizer-ExportAutoScalingGroupRecommendations"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "compute-optimizer:ExportAutoScalingGroupRecommendations"
                  - "compute-optimizer:GetAutoScalingGroupRecommendations"
                  - "autoscaling:DescribeAutoScalingGroups"
                Resource: "*"
        - PolicyName: "ComputeOptimizer-ExportEBSVolumeRecommendations"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "compute-optimizer:ExportEBSVolumeRecommendations"
                  - "compute-optimizer:GetEBSVolumeRecommendations"
                  - "EC2:DescribeVolumes"
                Resource: "*"
        - PolicyName: "ComputeOptimizer-ExportEC2InstanceRecommendations"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "compute-optimizer:ExportEC2InstanceRecommendations"
                  - "compute-optimizer:GetEC2InstanceRecommendations"
                  - "EC2:DescribeInstances"
                Resource: "*"
        - PolicyName: "ComputeOptimizer-ExportECSRecommendations"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "compute-optimizer:ExportECSServiceRecommendations"
                  - "compute-optimizer:GetECSServiceRecommendations"
                  - "compute-optimizer:GetECSServiceRecommendationProjectedMetrics"
                  - "ecs:ListServices"
                  - "ecs:ListClusters"
                Resource: "*"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Role must have an explicit RoleName for traceability"
          - id: W11
            reason: "Role is intended to describe a range of resources"