---
AWSTemplateFormatVersion: '2010-09-09'
Description: (DataCollection) Stack to enable link account to send data to central DataCollectionBus

Parameters:
  DataCollectionBusArn:
    Type: String
    Description: Centerlized DataCollection EventBus Arn in data collection account

Resources:
  DataCollectionRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub "HealthEventPutEvent-${AWS::AccountId}-${AWS::Region}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "events:PutEvents"
                Resource: 
                  - !Ref DataCollectionBusArn

  # Define an IAM Role for the AWS Events Rule with policy to get events from EB and put in Kinesis Firehose
  DefaultBusRuleHealth:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "EventBridge default rule for aws.health events"
      EventBusName: "default"
      EventPattern:
        source:
          - "aws.health"
          - "awshealthtest"
      Targets:
        - Arn: !Ref DataCollectionBusArn
          Id: DataCollectionRuleOnDefaultBus
          RoleArn: !GetAtt  DataCollectionRuleRole.Arn