---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - S3Objects
Description: Lambda to collect Org data and store in S3 
Parameters:
  QuicksightUserARN:
    Type: String
    Description: QuickSight ARN of the owning User
    Default: "arn:aws:quicksight:us-east-1:182071094551:user/default/vmindru"
  DestinationBucket:
    Type: String
    Description: Name of the S3 Bucket that is created to hold org data
    Default: cid-182071094551-shared
  DestinationBucketManifestKey:
    Type: String
    Description: Name of the S3 Bucket Key with Manifest
    Default: cid_rls/cid_rls.json
Resources:
  S3Object:
    Type: AWS::S3::Object
    Properties:
      Target:
        Bucket: !Ref DestinationBucket
        Key: README.md
        ContentType: text/markdown
      Body: !Sub |
        {
          "fileLocations": [
              {
                  "URIs": [
                      "s3:///${DestinationBucket}/${DestinationBucketManifestKey}",
                  ]
              }
          ],
          "globalUploadSettings": {
              "format": "CSV",
              "delimiter": ",",
              "textqualifier": "\"",
              "containsHeader": "true"
          \}
        \}
  QsRLSDatasource:
    Type: AWS::QuickSight::DataSource
    DependsOn: "S3Object"
    Properties:
      AwsAccountId: !Ref "AWS::AccountId"
      DataSourceId: "cid-rls-datasource"
      Name: "cid-rls-datasource"
      Type: S3
      DataSourceParameters:
        S3Parameters:
          ManifestFileLocation:
            Bucket: "182071094551rlsdata"
            Key: "cid_rls/cid_rls.json"
      Permissions:
        - Actions:
            - "quicksight:UpdateDataSourcePermissions"
            - "quicksight:DescribeDataSource"
            - "quicksight:DescribeDataSourcePermissions"
            - "quicksight:PassDataSource"
            - "quicksight:UpdateDataSource"
            - "quicksight:DeleteDataSource"
          Principal: !Ref QuicksightUserARN
  QsRLSDataSet:
    Type: AWS::QuickSight::DataSet
    DependsOn: "QsRLSDatasource"
    Properties:
      DataSetId: "cid-rls-dataset"
      AwsAccountId: !Ref "AWS::AccountId"
      Name: "cid-rls-dataset"
      ImportMode: SPICE
      Permissions:
        - Actions:
            - "quicksight:DeleteDataSet"
            - "quicksight:CreateIngestion"
            - "quicksight:CancelIngestion"
            - "quicksight:DescribeDataSet"
            - "quicksight:DescribeDataSetPermissions"
            - "quicksight:PassDataSet"
            - "quicksight:DescribeIngestion"
            - "quicksight:ListIngestions"
            - "quicksight:UpdateDataSetPermissions"
            - "quicksight:UpdateDataSet"
          Principal: !Ref QuicksightUserARN
      PhysicalTableMap:
        cid-rls-dataset:
          S3Source:
            DataSourceArn: !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:datasource/cid-rls-datasource"
            InputColumns:
              - Name: "UserName"
                Type: "STRING"
              - Name: "account_id"
                Type: "STRING"
              - Name: "payer_account_id"
                Type: "STRING"
